tests: Start osbuild-composer.socket
weldr/lorax pull request #1109
Opened 2021-01-25 13:20 UTC by atodorov

otherwise API socket isn't automatically started

Related: rhbz#1916684

Should address the failures seen in https://github.com/cockpit-project/bots/pull/1578

2021-01-25 14:04 UTC, atodorov commented
`composer-cli compose start test-http-server qcow2` fails. Likely with a depsolve problem.

2021-01-26 16:12 UTC, bcl approved these changes
Looks ok to me

2021-01-26 19:15 UTC, martinpitt requested changes
`subscription-manager attach --auto` now [fails in the tests](https://logs.cockpit-project.org/logs/pull-1109-20210126-141717-4eb8d845-rhel-8-4-osbuild-composer/log.html)

2021-01-26 19:15 UTC, martinpitt commented on tests/cli/lib/lib.sh
> -        systemctl start $BACKEND
It feels a bit weird that the commit message  says "start osbuild-composer.socket" for this removal?

2021-01-27 18:52 UTC, martinpitt approved these changes
Whee, thank you! :+1:

2021-01-28 11:25 UTC, merged