Add release info flags for livemedia-creator
weldr/lorax pull request #1264
Opened 2022-09-07 01:09 UTC by korewaChino

2022-09-07 16:46 UTC, bcl requested changes
Hi, thanks for the PR! Could you make the options match their counterparts from lorax? eg. If they have a short form include that, set the same metavar, etc. But leave out `required` of course. Also, final should be `opts.isfinal` to match as well.

2022-09-09 01:37 UTC, korewaChino commented
I have copied the flags from lorax, please check again.

2022-09-09 15:17 UTC, bcl requested changes
Other than that one change, this looks good.

2022-09-09 15:17 UTC, bcl commented on src/pylorax/cmdline.py
> +    parser.add_argument("-r", "--release", help="release information", required=True, metavar="RELEASE")
don't include `required`

2022-09-29 22:45 UTC, bcl commented
Fixed up, updated tests, merged to master. Thanks!

2022-09-29 22:45 UTC, closed without merging